create table previsaotemperatura(id bigint generated by default as identity (start with 100) not null primary key, diasemana varchar(200), tempMin double, tempMax double, humidade int, descricao varchar(250));


insert into previsaotemperatura (id, diasemana, tempMin, tempMax, humidade, descricao) values(2, 'Quinta 19/03' , 24 , 28 , 60 , 'Nuvens Espalhadas');
